baseURL = 'https://mhaddad-sec.me/'
languageCode = 'fr-fr'
title = 'Mohamed Haddad | SecOps'
theme = 'terminal'

[params]
  readMore = "Lire la suite"

[params.logo]
  logoText = 'mhaddad-sec@root: ~'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 20