baseURL = 'https://mhaddad-sec.me/'
languageCode = 'fr-fr'
title = 'Mohamed Haddad | SecOps'
theme = 'terminal'

[params]
  customCSS = ["css/custom.css"]

[params.logo]
  logoText = 'mhaddad-sec@root: ~'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 20